version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videostore
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/videostore.sql:/docker-entrypoint-initdb.d/videostore.sql

  app:
    build: ./app
    container_name: flask_app
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_NAME: videostore
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
