- name: Install Cert-Manager
  hosts: localhost
  vars:
    cert_manager_version: "v1.6.1"
    cert_manager_namespace: "cert-manager"
    add_repo_helm_repo_name: "jetstack"
    add_repo_helm_repo_url: "https://charts.jetstack.io"
  tasks:
    - name: Apply Cert-Manager CRDs
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml
        creates: /etc/kubernetes/manifests/cert-manager.crds.yaml

    - name: Create Cert-Manager namespace
      ansible.builtin.include_role:
        name: create_namespace
      vars:
        namespace_name: "{{ cert_manager_namespace }}"

    - name: Add Jetstack Helm repository
      ansible.builtin.include_role:
        name: add_repo
      vars:
        helm_repo_name: "{{ add_repo_helm_repo_name }}"
        helm_repo_url: "{{ add_repo_helm_repo_url }}"

    - name: Update Helm repositories
      ansible.builtin.include_role:
        name: update_repo

    - name: Install Cert-Manager
      ansible.builtin.command:
        cmd: helm install cert-manager jetstack/cert-manager --namespace {{ cert_manager_namespace }} --version {{ cert_manager_version }}
        creates: /etc/kubernetes/manifests/cert-manager.yaml
