name: Ansible

runs-on: ubuntu-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.12'

  - name: Install Ansible
    run: |
      python -m pip install --upgrade pip
      pip install ansible

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v3
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1

  - name: Install kubectl
    uses: azure/setup-kubectl@v3
    with:
      version: 'latest'

  - name: Install Helm
    uses: azure/setup-helm@v3
    with:
      version: 'latest'

  - name: Install Kubernetes pip package
    run: pip install kubernetes

  - name: Update kubeconfig
    run: aws eks update-kubeconfig --name gros-devops-project-cluster --region us-east-1

  - name: Run Cert-Manager playbook
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: ansible-playbook ansible/install_certmanager.yml

  - name: Run NGINX Ingress playbook
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: ansible-playbook ansible/install_nginx_ingress.yml

  - name: Run Rancher UI playbook
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: ansible-playbook ansible/install_rancher_ui.yml
