name: Infrastructure

runs-on: ubuntu-latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v3
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v1
    with:
      terraform_version: 1.10.4

  - name: Terraform Init
    run: terraform -chdir=terraform init

  - name: Terraform Plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: terraform -chdir=terraform plan

  - name: Terraform Apply
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: terraform -chdir=terraform apply -auto-approve
