name: CI

on:
  push:
    branches:
      - main
      - setup_env
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD: true

jobs:
  build:
    if: env.BUILD == 'true'
    uses: ./.github/workflows/build.yml

  infrastructure:
    uses: ./.github/workflows/infrastructure.yml

  ansible:
    uses: ./.github/workflows/ansible.yml
    needs: infrastructure
